name: Merge Checks
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: python setupz
        uses : actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: unit test - flake8 installs
        run: pip install flake8

      - name : run the flake8
        run: flake8 .
        
      - name: run python script 
        run: python addition.py
