name: PR Checks
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
              echo "Running tests for PR #${{ github.event.pull_request.number }}"
              echo "Another line of output"

      - name: Run the shell
        run: | 
            chmod +x add.sh
            ./add.sh
